language: python
python:
  - 3.6
sudo: false

env:
  global:
    # Doctr deploy key for Anaconda-Platform/livy-submit
    - secure: "TL+bVDf9N2eLvY58oUllquQT34X077o/cVFAXV1uk7rDEv0dlDYGWFuK0adL/isw4ntY3MzDyJ7l6hx0OPLRlgGwwtS78tMW8P+080aMZOisPWF
HCTT7Lndx24wWNXq5J2+1B1VTUr45g0Tw56XzbDc5v28J4Xd3kn9gc2aAZ/DanEtmwNBtalakFqjOyNGT5zh04RnPQUT39nupaqBjg+lN+xXRvQKAmBvF5jQVgmBUiU/fK
iJbPQGKmpUJtKN3jjqQYL5kJDh3bjFTz6aAvzN6HF/kFVYiwzumlYf3P5Hc8Kmw0IsjH97MIWJWAIeiJEUOkXLXNSMR72aFn2+hsPiCvZX4tHpMqrjgJlWcLSwlp9Xu1Qr
bMAvD7Rwy6xj4eO8HKS1BdeWtfRdoiYCeb5l0GNoV127SrRBb9WzD/ix/PIxLG6V3TFZ7K5NPHJLDe5GVn+2hnwy9srsQMlLE7q/xlIYQIYhtJTXgjo1s5iDDhKylgcem/
NE9dpGv9c1w4HuTq7wy6nlBtXrTMUw6nYAp0eCYRgAs984jdJQV+Mp4kRR5+NPvVBufQyFcdimvbjf4H5o4TS6r+A7pOJeoMWOQ5dt53MxdrxI10XqsiTQfZs3vuEtt4bC
Tht4FefXso6lDewMxDKRqz8DdamOAPcQq6ZyFLzd97qhpBlQrw1c="

install:
  - sudo apt-get update
  - set -e
  # from https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html#the-travis-yml-file
  - curl -X GET https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o mc.sh
  - bash mc.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

script: 
  - set -e
  - conda install --file requirements-dev.txt --file requirements.txt --file requirements-docs.txt -c conda-forge
  - source activate base && pushd docs && make html

after_success:
  - doctr deploy
